#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/xldesk/xldesk /usr/bin/xldesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/xldesk.service ]; then
			rm /etc/systemd/system/xldesk.service /usr/lib/systemd/system/xldesk.service /usr/lib/systemd/user/xldesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/xldesk/files/systemd/xldesk.service /usr/lib/systemd/system/xldesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/xldesk.service
		fi
		systemctl daemon-reload
		systemctl enable xldesk
systemctl start xldesk
	fi
fi
