name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: xldesk.xldesk
          version: "1.4.3"
          release-tag: "1.4.3"
          token: ${{ secrets.WINGET_TOKEN }}
